name: titanic

on:
    push:
        branches: [BreadKrum-patch-1]
    workflow_dispatch:
            
jobs:
    build:
        runs-on : ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run flake8 linting on src/ and api/
              run: flake8 src api

            - name: Run pytest
              run: pytest -q

            - name: setup docker buildx
              uses: docker/setup-buildx-action@v2

#            - name: Log in to Docker Hub
#              uses: docker/login-action@v2
#              with:
#                  username: ${{ secrets.breadkrum }}
#                  password: ${{ secrets.dckr_pat_KAJ4ASn-Y5hRlbILTbiMr0MQs3Q }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.breadkrum }}/titanic:latest

    deploy:
        runs-on: self-hosted
        steps:
            - name: Pull Docker image
              run: docker pull ${{ secrets.breadkrum }}/titanic:latest

            - name: restart container
              run: |
                  docker stop titanic || true
                  docker rm titanic || true
                  docker run -d --name titanic -p 8000:8000 ${{ secrets.breadkrum }}/titanic:latest
